#hasheq((name . "relaypilot")
        (display-name . "RelayPilot")
        (version . "0.1.0")
        (build . 1)
        (identifier . "ai.turinglambda.relaypilot")
        (release-channel . alpha)
        (url-schemes . ())
        (file-associations . ())
        (resources . ("examples"))
        (device-rpcs . (explain-route compile-engine-config))
        (macos-min-version . "14.0")
        (windows-min-version . "10.0.19041.0")
        (backend . "app/backend.rkt")
        (module . "backend")
        (entry . "start")
        (protocol . 1))

